# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0002_auto_20170220_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
