# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchProfile',
            fields=[
                ('twitch_id', models.CharField(max_length=254)),
                ('twitch_name', models.CharField(max_length=254)),
                ('twitch_display', models.CharField(max_length=254)),
                ('twitch_email', models.EmailField(max_length=254)),
                ('twitch_is_partnered', models.BooleanField(default=False)),
                ('twitch_user_type', models.CharField(max_length=254)),
                ('twitch_created', models.DateTimeField()),
                ('authorization_code', models.CharField(max_length=254)),
                ('access_token', models.CharField(max_length=254)),
                ('scopes', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name_plural': 'Twitch profiles',
                'verbose_name': 'Twitch profile',
            },
        ),
        migrations.CreateModel(
            name='TwitchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=254)),
                ('game', models.CharField(max_length=254)),
                ('delay', models.FloatField()),
                ('average_fps', models.FloatField()),
                ('current_viewers', models.IntegerField()),
                ('channel_id', models.CharField(max_length=254)),
                ('channel_status', models.CharField(max_length=254)),
                ('channel_mature', models.BooleanField(default=False)),
                ('channel_language', models.CharField(max_length=64)),
                ('went_live', models.DateTimeField()),
                ('is_playlist', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('total_views', models.BigIntegerField()),
                ('total_followers', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitchTrackingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=254, unique=True)),
                ('twitch_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='tracking_users',
            field=models.ManyToManyField(related_name='tracking_profile', to='twitch_stats.TwitchTrackingProfile', verbose_name='Tracking'),
        ),
    ]
