# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_stats', '0002_auto_20170220_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchtrackingprofile',
            name='twitch_id',
            field=models.TextField(max_length=254),
        ),
    ]
