# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_stats', '0003_auto_20170224_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
